### ISSUE TITLE
User can search for a game 

### ISSUE THREAD

**Issue by Alex-Davis0** [Alex-Davis0/Gaming-notepad#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will have be able to search through the library 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to search through the library
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93169087/154171657-569d72a3-2f1c-47db-bd5e-c49ba842b88a.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] create the jsx file for searching 
- [ ] create the search class and export it 
- [ ] setup the search bar in the Nav bar

### ☁️ Server

- [ ] Update `server/index.js` to use the get method with fetch to get what was searched 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
