### ISSUE TITLE
User can  view a library of all games

### ISSUE THREAD

**Issue by Alex-Davis0** [Alex-Davis0/Gaming-notepad#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view the library of games
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a library of all games on the database
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93169087/154145119-6af0cadc-372c-4aec-a7c6-405e2f0553eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add styles.css to src 
- [x] Setup CSS file 
- [x] Set background
- [x] Make nav bar
- [x]  Display the data from the API 

### ☁️ Server

- [x] Update `server/index.js` to fetch data needed 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
