### ISSUE TITLE
User can add notes to a game 

### ISSUE THREAD

**Issue by Alex-Davis0** [Alex-Davis0/Gaming-notepad#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

   User will have the ability to put notes on a game so they remember  what they where doing last time they played 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

they will be able to add a game to the database
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93169087/155239766-91c0e2bc-7fef-4647-a838-fb7b72e2afa2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] build database

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [x] Make the form
- [x] Make the handle submit 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
